services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      ssh:
        - default
    command: ["sh", "-c", "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn -b 0.0.0.0:8000 api.wsgi"]
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
      - worker

    env_file: .env
    volumes:
      - static_volume:/app/staticfiles
    environment:
      - POSTGRES_HOST=db
      - AMQP_URI=amqp://guest:guest@rabbitmq:5672
      
    develop:
      watch:
        - path: ./
          target: api
          action: rebuild  
  db:
    image: timescale/timescaledb:latest-pg16
    ports:
      - '5432:5432'
    container_name: postgresql
    volumes: 
      - pgdata:/var/lib/postgresql/data
    restart: always
    env_file: .env

  worker:
    build: .
    command: celery -A api worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - db
    environment:
      - POSTGRES_HOST=db
      - AMQP_URI=amqp://guest:guest@rabbitmq:5672

  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitdata:/var/lib/rabbitmq/


volumes:
  static_volume:
  pgdata:
  rabbitdata: