services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      ssh:
        - default
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env
    volumes:
      - static_volume:/app/staticfiles

    environment:
      - POSTGRES_HOST=db
      
    develop:
      watch:
        - path: ./
          target: api
          action: rebuild  
  db:
    image: timescale/timescaledb:latest-pg16
    ports:
      - '5432:5432'
    container_name: postgresql
    volumes: 
      - pgdata:/var/lib/postgresql/data
    restart: always
    env_file: .env

volumes:
  static_volume:
  pgdata:
